config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: 'tasks'
  # NEW BEFORE SHOW!!!
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get    'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch  'tasks/:id',      to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://kit.fontawesome.com/c9140bb46c.js"></script>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
<p><input id="check" type="checkbox" name="type[]">Completed</p>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<%  delete = '<i class="fa fa-trash" aria-hidden="false"></i>' %>
<% @tasks.each do |task| %>
<h2><input id="check" type="checkbox" name="type[]">
<%= link_to task.title, task_path(task) %>
<%= link_to delete.html_safe, destroy_path(task),
  method: :delete,
  data: {confirm: "Are you sure?"} %>
</h2>
<% end %>

<h2><%= link_to "+ Add a new task", tasks_new_path %></h2>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>

<p><input id="check" type="checkbox" name="type[]">
<%= @task.details %></p>

<h2><%= link_to "Edit", edit_path %></h2>

<p><%= link_to "Back to list", tasks_path %></p>


<%console%>